CREATE SCHEMA IF NOT EXISTS exam;

CREATE OR REPLACE FUNCTION exam.norm_text(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT nullif(
        btrim(
            regexp_replace(
                replace(value, chr(160), ' '),
                '[[:space:]]+',
                ' ',
                'g'
            )
        ),
        ''
    );
$$;

CREATE OR REPLACE FUNCTION exam.parse_import_number(value text)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
STRICT
AS $$
    SELECT replace(
        replace(exam.norm_text(value), ' ', ''),
        ',',
        '.'
    )::numeric;
$$;

CREATE OR REPLACE FUNCTION exam.parse_import_date(value text)
RETURNS date
LANGUAGE plpgsql
IMMUTABLE
STRICT
AS $$
DECLARE
    normalized text := exam.norm_text(value);
BEGIN
    IF normalized ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN
        RETURN normalized::date;
    ELSIF normalized ~ '^[0-9]{2}\.[0-9]{2}\.[0-9]{4}$' THEN
        RETURN to_date(normalized, 'DD.MM.YYYY');
    END IF;

    RAISE EXCEPTION 'Unsupported import date: %', value;
END;
$$;

CREATE TABLE IF NOT EXISTS exam.app_users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name text NOT NULL,
    first_name text NOT NULL,
    middle_name text NOT NULL,
    login text NOT NULL UNIQUE,
    role text NOT NULL CHECK (
        role IN (
            'Администратор',
            'Менеджер',
            'Авторизованный пользователь'
        )
    )
);

CREATE TABLE IF NOT EXISTS exam.products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    subcategory text NOT NULL,
    image_file text NOT NULL,
    name text NOT NULL,
    manufacturer text NOT NULL,
    description text NOT NULL,
    composition text NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    CONSTRAINT products_name_manufacturer_uq UNIQUE (name, manufacturer)
);

CREATE TABLE IF NOT EXISTS exam.sizes (
    shoe_size numeric(4, 1) PRIMARY KEY CHECK (shoe_size > 0)
);

CREATE TABLE IF NOT EXISTS exam.stock_items (
    product_id integer NOT NULL REFERENCES exam.products(product_id),
    shoe_size numeric(4, 1) NOT NULL REFERENCES exam.sizes(shoe_size),
    available_quantity integer NOT NULL CHECK (available_quantity >= 0),
    PRIMARY KEY (product_id, shoe_size)
);

CREATE TABLE IF NOT EXISTS exam.orders (
    order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date date NOT NULL DEFAULT CURRENT_DATE,
    customer_id integer NOT NULL REFERENCES exam.app_users(user_id),
    created_by_id integer NULL REFERENCES exam.app_users(user_id)
);

CREATE TABLE IF NOT EXISTS exam.order_items (
    order_id integer NOT NULL REFERENCES exam.orders(order_id) ON DELETE CASCADE,
    product_id integer NOT NULL,
    shoe_size numeric(4, 1) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (order_id, product_id, shoe_size),
    CONSTRAINT order_items_stock_item_fk
        FOREIGN KEY (product_id, shoe_size)
        REFERENCES exam.stock_items(product_id, shoe_size)
);

CREATE INDEX IF NOT EXISTS products_category_idx
    ON exam.products(category);

CREATE INDEX IF NOT EXISTS products_name_idx
    ON exam.products(name);

CREATE INDEX IF NOT EXISTS orders_date_idx
    ON exam.orders(order_date);

CREATE TABLE IF NOT EXISTS exam.stage_users (
    last_name text,
    first_name text,
    middle_name text,
    login text,
    role text
);

CREATE TABLE IF NOT EXISTS exam.stage_products (
    category text,
    subcategory text,
    image_file text,
    product_name text,
    manufacturer text,
    description text,
    composition text,
    price_text text
);

CREATE TABLE IF NOT EXISTS exam.stage_sizes (
    size_text text
);

CREATE TABLE IF NOT EXISTS exam.stage_stock_items (
    product_name text,
    manufacturer text,
    size_text text,
    quantity_text text
);

CREATE TABLE IF NOT EXISTS exam.stage_orders (
    order_number_text text,
    order_date_text text,
    customer_full_name text,
    category text,
    product_name text,
    manufacturer text,
    size_text text,
    quantity_text text,
    unit_price_text text
);
